import itertools

Import('env')

full_env = env.Clone(TEMPLATEDIR='templates')
full_env.LyGeometry('geometry')
full_env.TexGeometry('geometry')

yaml_sources = full_env.Glob('$BODYDIR/*.yaml')
filtered_catalog = full_env.FilteredCatalog(target='full_catalog.yaml', source=['$MUSICDIR/catalog.yaml', yaml_sources])
music_wrapper = full_env.LilypondWrapper(target='full_hymnal', source=filtered_catalog)
music_file = full_env.Lilypond('full_hymnal', music_wrapper)
texfile = full_env.Wrapper('fulltext', ['$TEMPLATEDIR/full.tex.tmp'] + yaml_sources + music_file)
if GetOption('twoup'):
    oneup_pdf = full_env.PDF('full_1up.pdf', 'full.tex')
    pdf_result = full_env.TwoUp('full.pdf', oneup_pdf)
else:
    pdf_result = full_env.PDF('full.pdf', 'full.tex')
