import itertools

Import('env')

env.LyGeometry('geometry')
env.TexGeometry('geometry')

yaml_sources = env.Glob('$BODYDIR/*.yaml')
music_wrapper = env.LilypondWrapper('full_hymnal', yaml_sources)
music_file = env.Lilypond('full_hymnal', music_wrapper)
texfile = env.Wrapper('fulltext', ['../templates/full.tex.tmp'] + yaml_sources + music_file)
env.Depends(texfile, env['calendar_file']) # rebuild if calendar changed, but does not appear in sources
if GetOption('twoup'):
    oneup_pdf = env.PDF('full_1up.pdf', 'full.tex')
    pdf_result = env.TwoUp('full.pdf', oneup_pdf)
else:
    pdf_result = env.PDF('full.pdf', 'full.tex')
