import itertools

Import('env')

full_env = env.Clone(TEMPLATEDIR='templates')
full_env.LyGeometry('geometry')
full_env.TexGeometry('geometry')

yaml_sources = full_env.Glob('$BODYDIR/*.yaml')
music_wrapper = full_env.LilypondWrapper('full_hymnal', yaml_sources)
music_file = full_env.Lilypond('full_hymnal', music_wrapper)
texfile = full_env.Wrapper('fulltext', ['$TEMPLATEDIR/full.tex.tmp'] + yaml_sources + music_file)
full_env.Depends(texfile, full_env['calendar_file']) # rebuild if calendar changed, but does not appear in sources
if GetOption('twoup'):
    oneup_pdf = full_env.PDF('full_1up.pdf', 'full.tex')
    pdf_result = full_env.TwoUp('full.pdf', oneup_pdf)
else:
    pdf_result = full_env.PDF('full.pdf', 'full.tex')
